require Module::Install;
require Module::Install::Fetch;
require Module::Install::Win32;
require Module::Install::ReadmeFromPod;
require Module::Install::WriteAll;
require Module::Install::Can;
require Module::Install::VersionCheck;
require Module::Install::Metadata;
require Module::Install::AckXXX;
require Module::Install::Package;
require Module::Install::Makefile;
require Module::Install::ManifestSkip;
require Module::Install::Stardoc;
require Module::Install::Base;
1;
