# This file gets loaded when an author runs Makefile.PL.
# It is intended to let a new author know which which plugins are required.
# This file was generated by Module::Install::Package.
# See the doc for that module for more information.
require Module::Install
    unless $INC{'Module/Install.pm'};
require Module::Install::AckXXX
    unless $INC{'Module/Install/AckXXX.pm'};
require Module::Install::Base
    unless $INC{'Module/Install/Base.pm'};
require Module::Install::Can
    unless $INC{'Module/Install/Can.pm'};
require Module::Install::Fetch
    unless $INC{'Module/Install/Fetch.pm'};
require Module::Install::Makefile
    unless $INC{'Module/Install/Makefile.pm'};
require Module::Install::ManifestSkip
    unless $INC{'Module/Install/ManifestSkip.pm'};
require Module::Install::Metadata
    unless $INC{'Module/Install/Metadata.pm'};
require Module::Install::Package
    unless $INC{'Module/Install/Package.pm'};
require Module::Install::ReadmeFromPod
    unless $INC{'Module/Install/ReadmeFromPod.pm'};
require Module::Install::Stardoc
    unless $INC{'Module/Install/Stardoc.pm'};
require Module::Install::VersionCheck
    unless $INC{'Module/Install/VersionCheck.pm'};
require Module::Install::Win32
    unless $INC{'Module/Install/Win32.pm'};
require Module::Install::WriteAll
    unless $INC{'Module/Install/WriteAll.pm'};
require Module::Package
    unless $INC{'Module/Package.pm'};
1;
